### ISSUE TITLE
配置密码就报错，不配置密码可以用

### ISSUE THREAD

**Issue by navyran** [sleeprite/rudis#1]
配置密码就报错，不配置密码可以用

**Comment by sleeprite** [comment]
配置密码后，在使用常规命令之前是否使用 auth 命令登录

**Comment by navyran** [comment]
> 配置密码后，在使用常规命令之前是否使用 auth 命令登录

直接使用的python的Redis客户端连接的，未直接使用命令连接

**Comment by sleeprite** [comment]
你使用的是哪个 lib，可以告知我，我在验证和修复后答复你

**Comment by navyran** [comment]
import redis
 r = redis.Redis(host='127.0.0.1', port=6379, password='12345')

**Comment by sleeprite** [comment]
该问题已修复，你可以下载 release 目录里最新的构建产物，并且我在 examples 新增了 demo.py，用于修复该错误的案例

https://github.com/sleeprite/rudis/blob/master/exmpales/demo.py

**Comment by sleeprite** [comment]
如果有需要，你可以再次打开这个 issues
