### ISSUE TITLE
bug report: receive wrong command will panic

### ISSUE THREAD

**Issue by DeadPoetSpoon** [sleeprite/rudis#12]
发送 `get` or `set a` 等错误命令会崩溃，并关闭TCP连接，关闭连接后再次连接命令无法正确运行

redis-cli 发送错误命令：

> 127.0.0.1:6379> get
> Error: Server closed the connection
> not connected> quit

再次连接：

> 127.0.0.1:6379> set a b
> Error: Server closed the connection

**Comment by sleeprite** [comment]
我在具体的命令内部增加了错误响应，来临时处理这个问题，我们可以继续在 #13 讨论长期的方案 https://github.com/sleeprite/rudis/commit/b3eff331a595e40e41d45463098cb3744a3d4c31
