### ISSUE TITLE
bug report: set PX 1 will get wrong command

### ISSUE THREAD

**Issue by DeadPoetSpoon** [sleeprite/rudis#14]
`set a XX` 将返回 null

应当区分：
1. 必要参数和可选参数
2. 参数位置

可以参考 [查看文件](https://github.com/DeadPoetSpoon/rudis/blob/test/parser/src/main.rs) 中的相关实现

可以在 #13 讨论完成后进行

**Comment by sleeprite** [comment]
已在 dev 分支，处理 set 命令可选参数的兼容性 https://github.com/sleeprite/rudis/commit/e823f836a1c1d24d2c3a39abdbdc233970c9befc
