### ISSUE TITLE
init_command_strategies() 这个方法的使用逻辑感觉不对呀。

### ISSUE THREAD

**Issue by MangerLe** [sleeprite/rudis#19]
每一个连接进来后都会去初始化一次这个。这个初始化的时候都是new一个hashmap.然后一顿插入。
我不知道自己是不是理解错了。这个应该只需要初始化一次就可以了。
rust初学者，有不对的地方望指出谢谢。

**Comment by sleeprite** [comment]
感谢指正，的确是这样的，随着链接的增长，造成了更多的内存占用，改进上你有什么建议

**Comment by DeadPoetSpoon** [comment]
> 感谢指正，的确是这样的，随着链接的增长，造成了更多的内存占用，改进上你有什么建议

每次连接完成离开作用区都会自动释放吧，只是每次都会把所有命令 INIT 一遍，可以先修改为函数，传入 命令名 返回对应的一个 `Command`

@MangerLe  可以看看 #13 的讨论，修改这部分代码涉及所有命令的修改，是个不少的工作量，可以先讨论，在命令适配完成后再整体优化

**Comment by MangerLe** [comment]
> 感谢指正，的确是这样的，随着链接的增长，造成了更多的内存占用，改进上你有什么建议

正在学习ing

**Comment by MangerLe** [comment]
> > 感谢指正，的确是这样的，随着链接的增长，造成了更多的内存占用，改进上你有什么建议
> 
> 每次连接完成离开作用区都会自动释放吧，只是每次都会把所有命令 INIT 一遍，可以先修改为函数，传入 命令名 返回对应的一个 `Command`
> 
> @MangerLe 可以看看 #13 的讨论，修改这部分代码涉及所有命令的修改，是个不少的工作量，可以先讨论，在命令适配完成后再整体优化

多些解答，我先学习学习
