### ISSUE TITLE
创建连接成功了，没问题，但是连不上。

### ISSUE THREAD

**Issue by ccpwcn** [sleeprite/rudis#2]
尝试使用RedisViewer，创建连接的时候，测试连接成功，点击连接进去的时候，报错，如下 图所示：

![image](https://github.com/sleeprite/rudis/assets/5465756/3d2c645a-1bea-49b1-8b53-4d43252d6ece)

**Comment by sleeprite** [comment]
在最新的 README.md 中，我是用 python 编写了一个简单的 web 可视化工具，如果你了解 python 可以直接使用，又或者参考编写一个工具出来

![image](https://github.com/sleeprite/rudis/assets/96010787/90d02fd1-2eab-40e2-a4e2-31fae685dc97)
