### ISSUE TITLE
value有限制长度吗？

### ISSUE THREAD

**Issue by navyran** [sleeprite/rudis#4]
value有限制长度吗？ 
存进入4000多个字符，取出来只有前470个字符
<img width="647" alt="image" src="https://github.com/user-attachments/assets/41883fe7-c5c2-4ef5-9875-25289421496d">

**Comment by sleeprite** [comment]
目前是固定长度的，整个命令固定 512，除去协议本身，value 刚好 470，之前的确没有考虑到这种 bigdata 的场景

**Comment by sleeprite** [comment]
我们已经修复了这个问题，你可以在下个版本验证

关联 Commit：https://github.com/sleeprite/rudis/commit/fc4bc0debc7080abf5628fc12b164ba32c5aa0e8
