### ISSUE TITLE
无法正确读取命令行参数”--save“

### ISSUE THREAD

**Issue by DeadPoetSpoon** [sleeprite/rudis#5]
`save` 格式为： \<seconds\> \<changes\>
[db/db_config.rs](https://github.com/sleeprite/rudis/blob/034a78816de7b6d5829971b5011eb95d43cd6b7e/src/db/db_config.rs#L265) 中 `get_save_or` 函数仅获取两位
如下可解决该问题，但不是获取命令行参数的最佳方案，在[persistence/rdb_scheduler.rs](https://github.com/sleeprite/rudis/blob/034a78816de7b6d5829971b5011eb95d43cd6b7e/src/persistence/rdb_scheduler.rs#L18) 中 `execute` 函数循环获取 `save` 参数对，现有的写法无法实现
```rust
fn get_save_or(default_save: Option<String>) -> Option<String> {
    let mut args = env::args().skip_while(|arg| arg != "--save").take(3); // 获取三位
    if args.next().is_none() {
        return default_save;
    }

    if let (Some(i), Some(c)) = (args.next(), args.next()) {
        Some(format!("{} {}", i, c)) // 拼接为正确格式
    } else {
        default_save
    }
}
```
建议将命令行参数的优先级提高在配置文件之前

**Comment by sleeprite** [comment]
已修复 https://github.com/sleeprite/rudis/commit/c9a7068bce3f107af7395ae400d73d00384bd2da

感谢你的建议，启动参数的优先级，的确应该大于配置文件，我们将在后续的提交中调整

**Comment by DeadPoetSpoon** [comment]
@sleeprite  如果愿意使用 [clap](https://docs.rs/clap/latest/clap/) 我可以帮助修改一下

**Comment by sleeprite** [comment]
@DeadPoetSpoon 在 main.rs 中的测试程序我们是否可以独立出去，来保证代码结构的清晰https://github.com/sleeprite/rudis/blob/master/src/main.rs
