### ISSUE TITLE
Rdb在load之前truncate

### ISSUE THREAD

**Issue by DeadPoetSpoon** [sleeprite/rudis#6]
[main.rs](https://github.com/sleeprite/rudis/blob/7138fc00fad088f6af6acb2d96c71e9bea13f04e/src/main.rs#L63) 中 `Rdb::new` 在 `Rdb::load` 之前，而在 [Rdb::new](https://github.com/sleeprite/rudis/blob/034a78816de7b6d5829971b5011eb95d43cd6b7e/src/persistence/rdb.rs#L33) 中 truncate，导致无法读取rdb中的数据
 
我修改 [persistence/rdb.rs#L33](https://github.com/sleeprite/rudis/blob/034a78816de7b6d5829971b5011eb95d43cd6b7e/src/persistence/rdb.rs#L33) 解决
```rust
OpenOptions::new().create(true).write(true).open(file_path).expect("Failed to open AOF file"),
```

**Comment by sleeprite** [comment]
感谢你提供的解决方案，已修复 https://github.com/sleeprite/rudis/commit/fec4da62efbf05ad5d949ce5596f125296f9be3a

你这边如果感兴趣帮助我们来完善 Rudis，欢迎提交一些 Pull requests

**Comment by DeadPoetSpoon** [comment]
感谢你们的工作， `rudis` 很棒，满足我的需求

我期望扩展 `rudis` 以支持当下我的工作，发现问题我会提供我力所能及的帮助

我也才学习rust不久，我的目标是实际的应用，在测试、文档方面或许能提供一些支持

正如 #3 中所讨论的，或许有一些规范以及你们的需求可以提供，以助于我更好地支持

下次有修改我将直接提交 `Pull requests` ， 但我之前没有相关经验，如有错误抱歉
