### ISSUE TITLE
redis-rs 高版本无法连接

### ISSUE THREAD

**Issue by DeadPoetSpoon** [sleeprite/rudis#7]
我在我的工程中试图使用 [redis-rs 0.24.0](https://docs.rs/redis/0.24.0/redis/index.html) 连接 `rudis` 但一直阻塞在 `redis::client::Client::get_connection` 

问题发生在 `redis-rs` 在 `0.23.4` 版本后，在完成连接后调用了 [CLIENT SETINFO](https://redis.io/docs/latest/commands/client-setinfo/) 命令（[src/connection.rs#L956](https://github.com/redis-rs/redis-rs/blob/redis-0.23.4/redis/src/connection.rs#L956)），`rudis` 目前不支持该命令并返回 `PONG` ，或许 `redis-rs` 无法正确获取命令结果以至于阻塞。

参照源码，我在 `Cargo.toml` 中修改 `redis-rs` 依赖解决，`features` 需包含 `disable-client-setinfo` ，其他为默认 `features`
```toml
redis = {version= "0.26.0",default-features = false,features=["acl","geospatial","script","streams","keep-alive","disable-client-setinfo"]}
```

或许目前 `CLIENT SETINFO` 命令直接返回 `OK` 什么也不做？

**Comment by sleeprite** [comment]
存在解决方案，暂时不处置
